[build]
command = "bundle exec jekyll build"
publish = "_site"

[build.environment]
RUBY_VERSION = "3.3.6"

[[redirects]]
from = "https://knirpsenstadt.netlify.app/*"
to = "https://knirpsenstadt,de/:splat"
status = 301
force = true
